<?php

namespace App\Tests\Functionel;

use App\Entity\Emplacement;
use App\Entity\FoodTruck;
use App\Tests\AbstractFunctionalApiTest;
use Doctrine\Common\Collections\ArrayCollection;

class PreventfoodTruckMoreThanAthreeAWeekervationTest extends AbstractFunctionalApiTest
{

    public $entityManager;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testPreventfoodTruckMoreThanAthreeAWeekervation():void
    {
        /**
         * test reservation d'un emplacement pendant les weekend
         */
        $client = static::createClient();
        $listeEmplacement = new ArrayCollection($this->entityManager->getRepository(Emplacement::class)->findAll());
        $listeFoodtruck = new ArrayCollection($this->entityManager->getRepository(FoodTruck::class)->findAll());
        //dd(range(1,3));
        //dd(range(34,38));
        //foreach (range(34,38) as $number)
        foreach (range(8,11) as $number)
        {
            $crawler = $client->request('POST', '/api/reservations', [
                'json' => [
                    "note" => "first reserv",
                    "emplacement" => "/api/emplacements/" . $listeEmplacement->next()->getId(),
                    "foodtruck" => "/api/foodtrucks/" . $listeFoodtruck->current()->getId(),
                    "reservationAt" => "2021-02-".$number
                ]]);

        }
        $this->assertResponseStatusCodeSame(400);
    }

}
