<?php

namespace App\Tests\Functionel;

use App\Entity\Emplacement;
use App\Entity\FoodTruck;
use App\Entity\Reservation;
use App\Tests\AbstractFunctionalApiTest;
use Doctrine\Common\Collections\ArrayCollection;

class PreventWeekendReservationTest extends AbstractFunctionalApiTest
{
    public $entityManager;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

        public function testPreventWeekendReservation():void
    {
        $listeEmplacement = new ArrayCollection($this->entityManager->getRepository(Emplacement::class)->findAll());

        $listeFoodtruck = new ArrayCollection($this->entityManager->getRepository(FoodTruck::class)->findAll());

        /**
         * test reservation d'un emplacement pendant les weekend
         */
        $client = static::createClient();
        $crawler = $client->request('POST', '/api/reservations', [
            'json' => [
                "note" => "first reserv",
                "emplacement" => "/api/emplacements/" . $listeEmplacement->next()->getId(),
                "foodtruck" => "/api/foodtrucks/" . $listeFoodtruck->next()->getId(),
                "reservationAt" => "2021-02-06"
            ]]);

        $this->assertResponseStatusCodeSame(400);
    }

}
